version: 2

models:
  - name: stg_customers
    column:
      - name: customer_id
        tests:
          - not null
          - unique
      - name: first_name
        tests:
          - not null
      - name: last_name
        tests:
          - not null
  - name: stg_orders
    column:
      - name: order_id
        tests:
          - not null
          - unique
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        tests:
          - not null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed']
  - name: stg_payments
    column:
      - name: payment_id
        tests:
          - not null
          - unique
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: payment_method
        tests:
          - not null
      - name: amount
        tests:
          - not null